### ISSUE TITLE
Tests failing for python 3

### ISSUE THREAD

**Issue by gunthercox** [matze/python-phant#3]
Tests seem to be failing under python 3. I tested the code manually under python 3 and no errors are thrown which leads me to believe that it is just a problem with the tests.

I have included the traceback with the results.

``` python
ERROR: test_stats (tests.RequestTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/gunthercox/python-phant/tests.py", line 45, in test_stats
    remaining, used = p.remaining_bytes, p.used_bytes
  File "/home/travis/build/gunthercox/python-phant/phant.py", line 96, in remaining_bytes
    return self._get_stat('remaining')
  File "/home/travis/build/gunthercox/python-phant/phant.py", line 119, in _get_stat
    self._stats = response.json()
  File "/home/travis/virtualenv/python3.4.1/lib/python3.4/site-packages/requests/models.py", line 753, in json
    encoding = guess_json_utf(self.content)
  File "/home/travis/virtualenv/python3.4.1/lib/python3.4/site-packages/requests/utils.py", line 612, in guess_json_utf
    nullcount = sample.count(_null)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by SergSlipushenko** [comment]
I hit this issue on httmock==1.2.3.
```python
Traceback (most recent call last):
  File "/home/sslypushenko/projects/refstack/refstack/tests/unit/test_api.py", line 255, in test_get_capabilities
    result = self.controller.get()
  File "/home/sslypushenko/projects/refstack/refstack/api/controllers/v1.py", line 206, in get
    json = response.json()
  File "/home/sslypushenko/projects/refstack/.tox/py34/lib/python3.4/site-packages/requests/models.py", line 809, in json
    encoding = guess_json_utf(self.content)
  File "/home/sslypushenko/projects/refstack/.tox/py34/lib/python3.4/site-packages/requests/utils.py", line 631, in guess_json_utf
    nullcount = sample.count(_null)
TypeError: Can't convert 'bytes' object to str implicitly
```
I know that you fixed this issue for dicts, but content response can be a list too.
It is a kind of example for from our code:
```python
        @httmock.all_requests
        def api_mock(url, request):
            headers = {'content-type': 'application/json'}
            content = [1,2,3]
            content = json.dumps(content)
            return httmock.response(200, content, headers, None, 5, request)
```
